remote_theme: BDHU/minimalist
title: Developed by Neato
description: "(C) 2020-2022 | CC BY-NC-SA 4.0"
logo: Resources/favicon.ico
sidebar:
  - name: GitHub Profile
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/neatodev
  - name: Project Repository
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
    link: https://github.com/neatodev/BmLauncherAsylumNET6
  - name: License
    icon: <i class="fa-solid fa-scale-balanced"></i>
    link: https://raw.githubusercontent.com/neatodev/BmLauncherAsylumNET6/master/LICENSE
  - name: Nexusmods Page
    icon: <img src="Resources/nexus_icon.ico" height="16" width="16" />
    link: https://www.nexusmods.com/batmanarkhamasylum/mods/117/
  - name: Donate
    icon: <i class="fa-brands fa-paypal"></i>
    link: https://www.paypal.com/donate/?hosted_button_id=LG7YTKP4JYN5S
    
github: [metadata]
color-scheme: auto
favicon: true
